spring:
  application:
    name: music-cloud-auth-server
server:
  port: 9062

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9060/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.security: debug