spring:
  application:
    name: music-cloud-pay-server
server:
  port: 9064


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9060/eureka/
  instance:
    prefer-ip-address: true